path:
    train_path: ../data/nof.csv
    dev_path: ../data/dev.csv
    test_path: ../data/dev.csv
    predict_path: ../data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: beomi/KcELECTRA-base
    saved_name: beomi/electra/

train:
    seed: 42
    gpus: 1
    batch_size: 32
    max_epoch: 10
    learning_rate: 3e-5
    logging_step: 1
wandb:
    wandb_username: rion_
    wandb_project: sts
    wandb_entity: sts_et
