path:
    train_path: ../../data/e_df.csv
    dev_path: ../../data/dev.csv
    test_path: ../../data/dev.csv
    predict_path: ../../data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: snunlp/KR-ELECTRA-discriminator
    saved_name: krelectra_model

train:
    seed: 42
    gpus: 1
    batch_size: 32
    max_epoch: 15
    learning_rate: 1e-5
    logging_step: 1
wandb:
    wandb_username: gwkim_22
    wandb_project: sts
    wandb_entity: sts_et
