path:
    train_path: ../../data/train_zero_e.csv
    dev_path: ../../data/dev_zero_e.csv
    test_path: ../../data/dev_zero_e.csv
    predict_path: ../../data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: snunlp/KR-ELECTRA-discriminator
    saved_name: snunlp/KR-ELECTRA-discriminator/zero_e_16_3e-5

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 30
    learning_rate: 1e-5
    logging_step: 5
wandb:
    wandb_username: seokhee
    wandb_project: sts
    wandb_entity: sts_et
