path:
    train_path: ../../data/e_df.csv
    dev_path: ../../data/dev.csv
    test_path: ../../data/dev.csv
    predict_path: ../../data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: monologg/koelectra-base-v3-discriminator
    saved_name: monologg/koelectra-base-v3-discriminator/e_df_16_1e-5

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 30
    learning_rate: 1e-5
    logging_step: 5
wandb:
    wandb_username: seokhee
    wandb_project: ELECTRA
    wandb_entity: sts_et
