path:
    train_path: ../../data/c_02_df.csv
    dev_path: ../../data/dev.csv
    test_path: ../../data/dev.csv
    predict_path: ../../data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: klue/roberta-base
    saved_name: base_model

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 20
    learning_rate: 1e-5
    logging_step: 1
wandb:
    wandb_username: seokhee
    wandb_project: sts
    wandb_entity: sts_et
