path:
    train_path: ../../data/nof.csv
    dev_path: ../../data/dev.csv
    test_path: ../../data/dev.csv
    predict_path: ../../data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: klue/roberta-large
    saved_name: klue/roberta-large/lr5e-6/nof

train:
    seed: 42
    gpus: 1
    batch_size: 8
    max_epoch: 30
    learning_rate: 5e-6
    logging_step: 1
wandb:
    wandb_username: seokhee
    wandb_project: Final_STS
    wandb_entity: sts_et
